export enum MenuEnum {
  FEATURES = "Features",
  FREE = "Free",
  A = "A",
  B = "B",
  C = "C",
}

export const PRICE_LISTS = [
  {
    id: 1,
    Features: "Number of pages",
    Free: 2,
    A: 10,
    B: 100,
    C: 250,
  },
  {
    id: 2,
    Features: "OCR support language",
    Free: "Khmer and English",
    A: "Khmer and English",
    B: "Khmer and English",
    C: "Khmer and English",
  },
  {
    id: 3,
    Features: "Export format",
    Free: "PDF and Image",
    A: "PDF and Image",
    B: "PDF and Image",
    C: "PDF and Image",
  },
  {
    id: 4,
    Features: "Text Editor",
    Free: "Yes",
    A: "Yes",
    B: "Yes",
    C: "Yes",
  },
  {
    id: 5,
    Features: "Cloud storage",
    Free: "0GB",
    A: "1GB",
    B: "5GB",
    C: "25GB",
  },
  {
    id: 6,
    Features: "Compress file",
    Free: "Yes",
    A: "Yes",
    B: "Yes",
    C: "Yes",
  },
  {
    id: 7,
    Features: "Web App",
    Free: "Yes",
    A: "Yes",
    B: "Yes",
    C: "Yes",
  },
  {
    id: 8,
    Features: "App Mobile",
    Free: "No",
    A: "No",
    B: "Yes",
    C: "Yes",
  },
  {
    id: 9,
    Features: "Windows App",
    Free: "No",
    A: "No",
    B: "No",
    C: "Yes",
  },
  {
    id: 10,
    Features: "Spelling correction",
    Free: "Yes",
    A: "Yes",
    B: "Yes",
    C: "Yes",
  },
  {
    id: 11,
    Features: "Rephrasing",
    Free: "No",
    A: "No",
    B: "Yes",
    C: "Yes",
  },
  {
    id: 12,
    Features: "Handwriting",
    Free: "No",
    A: "No",
    B: "No",
    C: "Yes",
  },
  {
    id: 13,
    Features: "Price pm",
    Free: 0,
    A: 1,
    B: 5,
    C: 10,
  },
];
